name: JabTracker
options:
  bundleIdPrefix: com.gannonhall
  deploymentTarget:
    iOS: "17.0"
  defaultConfig: Debug
  createIntermediateGroups: true
  
targets:
  JabTracker:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: JabTracker
        excludes:
          - "*.xcassets"
    resources:
      - path: JabTracker/Assets.xcassets
    settings:
      CURRENT_PROJECT_VERSION: "1"
      MARKETING_VERSION: "1.0"
      TARGETED_DEVICE_FAMILY: 1
      ENABLE_PREVIEWS: NO
      CODE_SIGN_ENTITLEMENTS: JabTracker/JabTracker.entitlements
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ZBZKKWF95G
      INFOPLIST_FILE: JabTracker/Info.plist
      
  JabTrackerTests:
    type: bundle.unit-test
    platform: iOS
    sources: [JabTrackerTests]
    settings:
      GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: JabTracker
      
  JabTrackerUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: [JabTrackerUITests]
    settings:
      GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: JabTracker

schemes:
  JabTracker:
    build:
      targets:
        JabTracker: all
        JabTrackerTests: [test]
        JabTrackerUITests: [test]
    test:
      targets:
        - JabTrackerTests
        - JabTrackerUITests
    run:
      commandLineArguments:
        "--force-onboarding": true
        "--reset-app-data": false
        "--ui-testing": false